language: node_js
node_js:
  - 4
sudo: false
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
# This is basically redundant (ends up getting run twice) as this gets called
# by npm on install due to the prepublish script in package.json.
script:
  - gulp dist
